### PR TITLE
Game Over Screen

### PR DESCRIPTION
**Pull request by realmatthewpeng**
Game ends after 6 minutes.
- Can change duration in setup.json ("game_duration_seconds")
- Winning team is teleported in front of the bear
- Losing team is teleported to the side of the bear
- Text displays which team (blue or red) wins
- Game clock starts only when all players have selected their player (change "min_players_to_start" in setup.json)

### CODE REVIEW

**Review by Alanine42 — CHANGES_REQUESTED** [review]
after clicking space from the lobby screen I am spawned here and cannot move. 

image

looks like the server isn't responding to client's movement requests.

**Comment by Alanine42** [comment]
are the characters supposed to look like this (back)?

image

**Comment by Alanine42** [comment]
the game also ended quite early for me (way less than 6 minutes)

**Comment by realmatthewpeng** [comment]
> after clicking space from the lobby screen I am spawned here and cannot move.
> 
> image
> 
> looks like the server isn't responding to client's movement requests.

For future other's reference: you need to lock in your character in the lobby.

**Comment by realmatthewpeng** [comment]
> the game also ended quite early for me (way less than 6 minutes)

I accidentally changed the setup.json setting to 60 in my last commit. you need to change it to 360.

**Comment by realmatthewpeng** [comment]
> are the characters supposed to look like this (back)?
> 
> image

I didn't force the characters to look at the camera, so for now, yes. Actually, I think I need to make a small change so the players can still spin around.

**Comment by Alanine42** [comment]
I somehow get this screen (only difference in-game was I death-swapped with another player)

image

**Comment by realmatthewpeng** [comment]
> I somehow get this screen (only difference in-game was I death-swapped with another player)
> 
> image

Ah yes. That is the case when the scores are tied, so the players are not moved to the winning location. I just make it so BLUE wins for now.

**Comment by Alanine42** [comment]
> > I somehow get this screen (only difference in-game was I death-swapped with another player)
> > image
> 
> Ah yes. That is the case when the scores are tied, so the players are not moved to the winning location. I just make it so BLUE wins for now.

ahh i see, tie condition. makes sense!

**Review by Alanine42 — APPROVED** [review]
lgtm. 
nit: add tie case (tho not likely to happen hhh)

nit: enable players spin around

**Comment by realmatthewpeng** [comment]
> lgtm. nit: add tie case (tho not likely to happen hhh)
> 
> nit: enable players spin around

tie case --> blue wins (can change)
players spin around --> nvm was working all along

**Comment by Alanine42** [comment]
> > lgtm. nit: add tie case (tho not likely to happen hhh)
> > nit: enable players spin around
> 
> tie case --> blue wins (can change) players spin around --> nvm was working all along

I see, no problem them!

**Review by AnnLe4869 — APPROVED** [review]

**Review by Alanine42 — APPROVED** [review]
Reapprove

**Pull request merged**
