### PR TITLE
Toon Shading! (Cel shading)

### PR DESCRIPTION
**Pull request by benjxia**
Added support for toon shading.

### CODE REVIEW

**Comment by realmatthewpeng** [comment]
When I run client I get the following error:
`Failed to compile fragment shader
ERROR: 0:36: '{' : syntax error: syntax error`

**Comment by benjxia** [comment]
> When I run client I get the following error: `Failed to compile fragment shader ERROR: 0:36: '{' : syntax error: syntax error`

why does macos not allow that syntax...

**Review by realmatthewpeng — APPROVED** [review]
Ran the program. As far as I could tell everything looked correct? Understanding the code, of course, is beyond me.

**Review by Melody-Ruth — APPROVED** [review]
It runs correctly on my computer. Honestly I don't really understand the graphics code, but nothing jumps out at me as bad.

**Review by Alanine42 — APPROVED** [review]
lgtm works on my machine

**Review by Metarus — APPROVED** [review]
tested, lgtm

**Pull request merged**
