### PR TITLE
Shadows

### PR DESCRIPTION
**Pull request by benjxia**
Added shadows. Also did a decent amount of refactoring shaders and such

### CODE REVIEW

**Review by Metarus — APPROVED** [review]
I have to use the regular shaders for testing this (because my lightweight one does not have shadows), so I have complete dogwater FPS but they're the most beautiful frames I've ever seen. Looks good and I don't fully understand the graphics code.

**Review by Melody-Ruth — APPROVED** [review]
Lgtm! Ran it on my machine and the shadows are beautiful!

**Review by Alanine42 — APPROVED** [review]
lgtm works on my machine, also no conflict with the bullets branch

**Comment by Alanine42** [comment]
i'll move my shader classes to the bottom

**Comment by Alanine42** [comment]
ok done merging my line shader stuffs. built and tested. 

need another approval -_-

**Comment by Alanine42** [comment]
The bullet trail seems to disappear when client 0 spawns and shoots at the warren bear. Is it because some optimization or the ordering of rendering pipeline?

**Review by AnnLe4869 — APPROVED** [review]
Work really well. And I finally notice that the character ears are moving. Pretty cute if I would say so

**Comment by benjxia** [comment]
are bullets always supposed to aim towards the origin?

**Comment by Alanine42** [comment]
> are bullets always supposed to aim towards the origin?

no

**Comment by AnnLe4869** [comment]
> > are bullets always supposed to aim towards the origin?
> 
> no

just notice this. The bullet trajectory is blur the closer you shoot toward the bear

**Review by AnnLe4869 — APPROVED** [review]
This changes seem to fix the above mentioned bug with bullet trail

**Comment by Alanine42** [comment]
> > > are bullets always supposed to aim towards the origin?
> > 
> > 
> > no
> 
> just notice this. The bullet trajectory is blur the closer you shoot toward the bear

yea I switched to rendering a rectangular prism so it shouldn't blur in any direction now (slightly more vertices) (try it out)

**Pull request merged**
