### PR TITLE
Audio setup

### PR DESCRIPTION
**Pull request by AnnLe4869**
I have setup some very basic audio that can play audio and explosion sound periodically and jump sound on keyboard event. Will look into how to do the partial sound
I also setup the config such that we can read all config from inside a single json file. like this

```std::cout << "My name is " << SetupParser::getValue("name") << std::endl;```
right now I put some example setup in the common/setup.json but I image we can do more with this.

### CODE REVIEW

**Review by Metarus — APPROVED** [review]
lgtm

**Review by realmatthewpeng — APPROVED** [review]
MERGE MERGE MERGE

**Review by Alanine42 — APPROVED** [review]
appproooveeee thhiiss

**Comment by Alanine42** [comment]
finnnalllly

**Pull request merged**
