### PR TITLE
Skybox + Animated River

### PR DESCRIPTION
**Pull request by benjxia**
Added skybox with support for transparentskyboxes so we can also have the time become oranger as the sun moves.

Added river animations

### CODE REVIEW

**Comment by benjxia** [comment]
Also added Joanne's new collision map and stuff

**Comment by realmatthewpeng** [comment]
Screen Shot 2024-06-04 at 9 52 50 PM

Skybox is supposed to look like this right

**Comment by benjxia** [comment]
> Screen Shot 2024-06-04 at 9 52 50 PM
> 
> Skybox is supposed to look like this right

Yes, until we get an actual skybox

**Review by realmatthewpeng — APPROVED** [review]
Looks good!

**Review by Alanine42 — APPROVED** [review]
i see 3 red triangles, works

**Pull request merged**
