### PR TITLE
Lerp fix

### PR DESCRIPTION
**Pull request by Alanine42**
this is a patch pr

- disable all collision and movement request systems during the lerp
- moving sun dynamic shadows 
    - works but too much movement (like a circus)
- add billboard tags above players and the egg
    - needs better art

- removed debug prints and draws (world axis in bullet trail, rotating sun clock, etc.)

- removed "import images upside down" after importing all 2D UI assets.

### CODE REVIEW

**Review by Metarus — APPROVED** [review]
still laggy on my machine ;-; but seems to do everything it claims to, lgtm

**Review by Melody-Ruth — APPROVED** [review]
Lgtm! Seems to run fine

**Review by benjxia — APPROVED** [review]
if it doesnt break then it probably works

**Review by realmatthewpeng — APPROVED** [review]
Beginning to lag but it works

**Pull request merged**
