### PR TITLE
UI lobby screen

### PR DESCRIPTION
**Pull request by AnnLe4869**
The players can select characters and see what their teammate is selecting. Once they lock into a character they cannot change it. Can see this lock in status on other players. The game will start immediately once all 4 players are locked in

https://github.com/ucsd-cse125-sp24/group5/assets/39579697/44d4bee3-7b7e-46f7-9476-132eb77e554b

EDIT: for testing you can join the game immediately by hitting Space. Can remove this on official launch

### CODE REVIEW

**Comment by Alanine42** [comment]
the rightmost column is cut off. prolly because my screen size is smaller than 1920x1080?

image

**Comment by AnnLe4869** [comment]
> the rightmost column is cut off. prolly because my screen size is smaller than 1920x1080?
> 
> image

I believe so. I hardcoded the lobby size to be 1920x1080

**Review by Alanine42 — APPROVED** [review]
works great on my machine (except for some minor content cut-offs), thanks for setting up the character selection screen!

**Review by realmatthewpeng — APPROVED** [review]
Looks good to me

**Pull request merged**
