### PR TITLE
Cartoon outlines

### PR DESCRIPTION
**Pull request by benjxia**
Added cartoon outlines to shader

### CODE REVIEW

**Review by realmatthewpeng — APPROVED** [review]
Seems like magic to me, but works on my machine.

**Comment by benjxia** [comment]
> Seems like magic to me, but works on my machine.

who said it wasn't magic

**Review by Alanine42 — APPROVED** [review]
awesome +999

**Review by Melody-Ruth — APPROVED** [review]
It looks good on my machine! Outlines are neat.
lgtm

**Review by Metarus — APPROVED** [review]
a little laggy on my mac, but it looked smoother on Melody's computer and it's not unusable. as long as it runs better on the main running machines it's fine

**Pull request merged**
